# Generated by Django 5.1.5 on 2025-01-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='secret_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
